server:
  port: 8080
  contextPath: /SpringBootCRUDApp

spring:
  profiles: local, default
datasource:
  sampleapp:
    url: jdbc:h2:~/test
    username: vivek
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect

spring:
  profiles: prod
datasource:
  sampleapp:
    url: jdbc:mysql://127.0.0.1:3306/vivek
    username: vivek
    password: vivek
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
